config/routes.rb
Rails.application.routes.draw do
  resources :finances

  resources :quotes

  resources :inventories

  resources :customers

  resources :employees

  root 'quotes#index'

end

app/models/finance.rb
class Finance < ActiveRecord::Base
end

app/controllers/finances_controller.rb
class FinancesController < ApplicationController
  before_action :set_finance, only: [:show, :edit, :update, :destroy]

  # GET /finances
  # GET /finances.json
  def index
    @finances = Finance.all
  end

  # GET /finances/1
  # GET /finances/1.json
  def show
  end

  # GET /finances/new
  def new
    @finance = Finance.new
  end

  # GET /finances/1/edit
  def edit
  end

  # POST /finances
  # POST /finances.json
  def create
    @finance = Finance.new(finance_params)

    respond_to do |format|
      if @finance.save
        format.html { redirect_to @finance, notice: 'Finance was successfully created.' }
        format.json { render :show, status: :created, location: @finance }
      else
        format.html { render :new }
        format.json { render json: @finance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /finances/1
  # PATCH/PUT /finances/1.json
  def update
    respond_to do |format|
      if @finance.update(finance_params)
        format.html { redirect_to @finance, notice: 'Finance was successfully updated.' }
        format.json { render :show, status: :ok, location: @finance }
      else
        format.html { render :edit }
        format.json { render json: @finance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /finances/1
  # DELETE /finances/1.json
  def destroy
    @finance.destroy
    respond_to do |format|
      format.html { redirect_to finances_url, notice: 'Finance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_finance
      @finance = Finance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def finance_params
      params.require(:finance).permit(:interest, :principal, :payment, :interest_rate, :sales_tax, :start_date)
    end
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/views/finances/_form.html.erb
<%= form_for(@finance) do |f| %>
  <% if @finance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@finance.errors.count, "error") %> prohibited this finance from being saved:</h2>

      <ul>
      <% @finance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :interest %><br>
    <%= f.text_field :interest %>
  </div>
  <div class="field">
    <%= f.label :principal %><br>
    <%= f.text_field :principal %>
  </div>
  <div class="field">
    <%= f.label :payment %><br>
    <%= f.text_field :payment %>
  </div>
  <div class="field">
    <%= f.label :interest_rate %><br>
    <%= f.text_field :interest_rate %>
  </div>
  <div class="field">
    <%= f.label :sales_tax %><br>
    <%= f.text_field :sales_tax %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/finances/edit.html.erb
<h1>Editing Finance</h1>

<%= render 'form' %>

<%= link_to 'Show', @finance %> |
<%= link_to 'Back', finances_path %>

app/views/finances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Finances</h1>

<table>
  <thead>
    <tr>
      <th>Interest</th>
      <th>Principal</th>
      <th>Payment</th>
      <th>Interest rate</th>
      <th>Sales tax</th>
      <th>Start date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @finances.each do |finance| %>
      <tr>
        <td><%= finance.interest %></td>
        <td><%= finance.principal %></td>
        <td><%= finance.payment %></td>
        <td><%= finance.interest_rate %></td>
        <td><%= finance.sales_tax %></td>
        <td><%= finance.start_date %></td>
        <td><%= link_to 'Show', finance %></td>
        <td><%= link_to 'Edit', edit_finance_path(finance) %></td>
        <td><%= link_to 'Destroy', finance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Finance', new_finance_path %>

app/views/finances/new.html.erb
<h1>New Finance</h1>

<%= render 'form' %>

<%= link_to 'Back', finances_path %>

app/views/finances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Interest:</strong>
  <%= @finance.interest %>
</p>

<p>
  <strong>Principal:</strong>
  <%= @finance.principal %>
</p>

<p>
  <strong>Payment:</strong>
  <%= @finance.payment %>
</p>

<p>
  <strong>Interest rate:</strong>
  <%= @finance.interest_rate %>
</p>

<p>
  <strong>Sales tax:</strong>
  <%= @finance.sales_tax %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @finance.start_date %>
</p>

<%= link_to 'Edit', edit_finance_path(@finance) %> |
<%= link_to 'Back', finances_path %>